import { Routes } from '@angular/router';
import { authGuard } from './guards/auth.guard';

export const routes: Routes = [
  { path: 'login', loadComponent: () => import('./pages/login/login.component').then(m => m.LoginComponent) },
  {
    path: '',
    canActivate: [authGuard],
    children: [
      { path: '', redirectTo: 'dashboard', pathMatch: 'full' },
      { path: 'dashboard', loadComponent: () => import('./pages/dashboard/dashboard.component').then(m => m.DashboardComponent) },
      { path: 'tournaments', loadComponent: () => import('./pages/tournaments/tournaments.component').then(m => m.TournamentsComponent) },
      { path: 'tournaments/new', loadComponent: () => import('./pages/tournament-form/tournament-form.component').then(m => m.TournamentFormComponent) },
      { path: 'tournaments/:id/edit', loadComponent: () => import('./pages/tournament-form/tournament-form.component').then(m => m.TournamentFormComponent) },
      { path: 'tournaments/:id', loadComponent: () => import('./pages/tournament-detail/tournament-detail.component').then(m => m.TournamentDetailComponent) },
      { path: 'users', loadComponent: () => import('./pages/users/users.component').then(m => m.UsersComponent) },
      { path: 'users/:id', loadComponent: () => import('./pages/user-detail/user-detail.component').then(m => m.UserDetailComponent) },
      { path: 'promos', loadComponent: () => import('./pages/promos/promos.component').then(m => m.PromosComponent) },
      { path: 'accounting', loadComponent: () => import('./pages/accounting/accounting.component').then(m => m.AccountingComponent) },
      { path: 'monitor', loadComponent: () => import('./pages/monitor/monitor.component').then(m => m.MonitorComponent) },
      { path: 'match-formats', loadComponent: () => import('./pages/match-formats/match-formats.component').then(m => m.MatchFormatsComponent) },
      { path: 'match-formats/new', loadComponent: () => import('./pages/match-format-form/match-format-form.component').then(m => m.MatchFormatFormComponent) },
      { path: 'match-formats/:id/edit', loadComponent: () => import('./pages/match-format-form/match-format-form.component').then(m => m.MatchFormatFormComponent) },
      { path: 'match-formats/:id', loadComponent: () => import('./pages/match-format-detail/match-format-detail.component').then(m => m.MatchFormatDetailComponent) },
      { path: 'table-themes', loadComponent: () => import('./pages/table-themes/table-themes.component').then(m => m.TableThemesComponent) },
      { path: 'table-themes/new', loadComponent: () => import('./pages/table-theme-form/table-theme-form.component').then(m => m.TableThemeFormComponent) },
      { path: 'table-themes/:id/edit', loadComponent: () => import('./pages/table-theme-form/table-theme-form.component').then(m => m.TableThemeFormComponent) },
      { path: 'table-themes/:id', loadComponent: () => import('./pages/table-theme-detail/table-theme-detail.component').then(m => m.TableThemeDetailComponent) },
      { path: 'robot-avatars', loadComponent: () => import('./pages/robot-avatars/robot-avatars.component').then(m => m.RobotAvatarsComponent) },
      { path: 'robot-avatars/new', loadComponent: () => import('./pages/robot-avatar-form/robot-avatar-form.component').then(m => m.RobotAvatarFormComponent) },
      { path: 'robot-avatars/:id/edit', loadComponent: () => import('./pages/robot-avatar-form/robot-avatar-form.component').then(m => m.RobotAvatarFormComponent) },
      { path: 'player-avatars', loadComponent: () => import('./pages/player-avatars/player-avatars.component').then(m => m.PlayerAvatarsComponent) },
      { path: 'player-avatars/new', loadComponent: () => import('./pages/player-avatar-form/player-avatar-form.component').then(m => m.PlayerAvatarFormComponent) },
      { path: 'player-avatars/:id/edit', loadComponent: () => import('./pages/player-avatar-form/player-avatar-form.component').then(m => m.PlayerAvatarFormComponent) },
      { path: 'score-config', loadComponent: () => import('./pages/score-config/score-config.component').then(m => m.ScoreConfigComponent) },
      { path: 'help', loadComponent: () => import('./pages/help/help.component').then(m => m.HelpComponent) },
    ],
  },
  { path: '**', redirectTo: 'dashboard' },
];
