module.exports = {
  apps: [
    {
      name: 'kydos-api',
      cwd: './server',
      script: './node_modules/.bin/tsx',
      args: 'src/index.ts',
      interpreter: 'none',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      max_restarts: 15,
      min_uptime: '10s',
      restart_delay: 3000,
      max_memory_restart: '512M',
      out_file: '/var/log/kydos/api-out.log',
      error_file: '/var/log/kydos/api-err.log',
      merge_logs: true,
      time: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      env: {
        NODE_ENV: 'production',
        PORT: 8881,
        MONGO_URI: 'mongodb://root:toor@127.0.0.1:27017/beloteKK13?authSource=admin',
        JWT_SECRET: 'kydos-prod-jwt-secret-changez-moi-en-vrai-64-chars-minimum-svp',
        CORS_ORIGIN: '*',
      },
    },
    {
      name: 'kydos-mobile',
      cwd: './mobile',
      script: './node_modules/.bin/vite',
      args: 'preview --host 0.0.0.0 --port 8882 --strictPort',
      interpreter: 'none',
      instances: 1,
      exec_mode: 'fork',
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      max_memory_restart: '256M',
      out_file: '/var/log/kydos/mobile-out.log',
      error_file: '/var/log/kydos/mobile-err.log',
      merge_logs: true,
      time: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      env: { NODE_ENV: 'production' },
    },
  ],
};
